// Generated by gencpp from file webapp/user_input.msg
// DO NOT EDIT!


#ifndef WEBAPP_MESSAGE_USER_INPUT_H
#define WEBAPP_MESSAGE_USER_INPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace webapp
{
template <class ContainerAllocator>
struct user_input_
{
  typedef user_input_<ContainerAllocator> Type;

  user_input_()
    : direction()
    , speed()  {
    }
  user_input_(const ContainerAllocator& _alloc)
    : direction(_alloc)
    , speed(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::webapp::user_input_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webapp::user_input_<ContainerAllocator> const> ConstPtr;

}; // struct user_input_

typedef ::webapp::user_input_<std::allocator<void> > user_input;

typedef boost::shared_ptr< ::webapp::user_input > user_inputPtr;
typedef boost::shared_ptr< ::webapp::user_input const> user_inputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webapp::user_input_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webapp::user_input_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::webapp::user_input_<ContainerAllocator1> & lhs, const ::webapp::user_input_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::webapp::user_input_<ContainerAllocator1> & lhs, const ::webapp::user_input_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace webapp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::webapp::user_input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webapp::user_input_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webapp::user_input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webapp::user_input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webapp::user_input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webapp::user_input_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webapp::user_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cfec82bafd42343d86626b1cd93e67da";
  }

  static const char* value(const ::webapp::user_input_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcfec82bafd42343dULL;
  static const uint64_t static_value2 = 0x86626b1cd93e67daULL;
};

template<class ContainerAllocator>
struct DataType< ::webapp::user_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webapp/user_input";
  }

  static const char* value(const ::webapp::user_input_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webapp::user_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string direction\n"
"string speed\n"
;
  }

  static const char* value(const ::webapp::user_input_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webapp::user_input_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct user_input_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webapp::user_input_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::webapp::user_input_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
    s << indent << "speed: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEBAPP_MESSAGE_USER_INPUT_H
