// Generated by gencpp from file serial_communication/ultrasonic_data.msg
// DO NOT EDIT!


#ifndef SERIAL_COMMUNICATION_MESSAGE_ULTRASONIC_DATA_H
#define SERIAL_COMMUNICATION_MESSAGE_ULTRASONIC_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_communication
{
template <class ContainerAllocator>
struct ultrasonic_data_
{
  typedef ultrasonic_data_<ContainerAllocator> Type;

  ultrasonic_data_()
    : l(0)
    , r(0)
    , b(0)  {
    }
  ultrasonic_data_(const ContainerAllocator& _alloc)
    : l(0)
    , r(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int16_t _l_type;
  _l_type l;

   typedef int16_t _r_type;
  _r_type r;

   typedef int16_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::serial_communication::ultrasonic_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_communication::ultrasonic_data_<ContainerAllocator> const> ConstPtr;

}; // struct ultrasonic_data_

typedef ::serial_communication::ultrasonic_data_<std::allocator<void> > ultrasonic_data;

typedef boost::shared_ptr< ::serial_communication::ultrasonic_data > ultrasonic_dataPtr;
typedef boost::shared_ptr< ::serial_communication::ultrasonic_data const> ultrasonic_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_communication::ultrasonic_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_communication::ultrasonic_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_communication::ultrasonic_data_<ContainerAllocator1> & lhs, const ::serial_communication::ultrasonic_data_<ContainerAllocator2> & rhs)
{
  return lhs.l == rhs.l &&
    lhs.r == rhs.r &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_communication::ultrasonic_data_<ContainerAllocator1> & lhs, const ::serial_communication::ultrasonic_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::serial_communication::ultrasonic_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_communication::ultrasonic_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_communication::ultrasonic_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_communication::ultrasonic_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_communication::ultrasonic_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_communication::ultrasonic_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_communication::ultrasonic_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b84b3d698239ad2fd054a4286e165219";
  }

  static const char* value(const ::serial_communication::ultrasonic_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb84b3d698239ad2fULL;
  static const uint64_t static_value2 = 0xd054a4286e165219ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_communication::ultrasonic_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_communication/ultrasonic_data";
  }

  static const char* value(const ::serial_communication::ultrasonic_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_communication::ultrasonic_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 l\n"
"int16 r\n"
"int16 b\n"
;
  }

  static const char* value(const ::serial_communication::ultrasonic_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_communication::ultrasonic_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.l);
      stream.next(m.r);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultrasonic_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_communication::ultrasonic_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_communication::ultrasonic_data_<ContainerAllocator>& v)
  {
    s << indent << "l: ";
    Printer<int16_t>::stream(s, indent + "  ", v.l);
    s << indent << "r: ";
    Printer<int16_t>::stream(s, indent + "  ", v.r);
    s << indent << "b: ";
    Printer<int16_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_COMMUNICATION_MESSAGE_ULTRASONIC_DATA_H
